d1 <- read.table("household_power_consumption.txt", sep=";", skip=grep("1/2/2007", readLines("household_power_consumption.txt")), nrows = 2879)
names(d1) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_Intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
ds <- as.character(d1 $Date)
ts <- as.character(d1 $Time)
dT <- paste(ds, ts, sep = " ")
truedT <- strptime(dT, "%d/%m/%Y %H:%M:%S")
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1))
plot(truedT, data1 $Global_active_power, type = "l", ylab = "Global Active Power", xlab="")
plot(truedT, data1 $Voltage, type = "l", ylab = "Voltage", xlab="datetime")
with(d1, plot(truedT, Sub_metering_1, type = "l", xlab = "", ylab = "Energy Sub Metering"))
with(d1, points(truedT, Sub_metering_2, type = "l", col = "red"))
with(d1, points(truedT, Sub_metering_3, type = "l", col = "blue"))
legend("topright", lty = "solid", lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n")
plot(truedT, data1 $Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab="datetime")
dev.copy(png, file = "plot4.png")
dev.off()