d1 <- read.table("household_power_consumption.txt", sep=";", skip=grep("1/2/2007", readLines("household_power_consumption.txt")), nrows = 2879)
names(d1) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_Intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
ds <- as.character(d1 $Date)
ts <- as.character(d1 $Time)
dT <- paste(ds, ts, sep = " ")
truedT <- strptime(dT, "%d/%m/%Y %H:%M:%S")
with(d1, plot(truedT, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
with(d1, points(truedT, Sub_metering_2, type = "l", col = "red"))
with(d1, points(truedT, Sub_metering_3, type = "l", col = "blue"))
legend("topright", lty = "solid", lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()